### PR TITLE
Publisher/Subscriber Tutorial

### PR DESCRIPTION
**Pull request by JZ0024**
[talker.txt](https://github.com/robotics-at-maryland/qubo/files/2454316/talker.txt)
[listener.txt](https://github.com/robotics-at-maryland/qubo/files/2454317/listener.txt)

### CODE REVIEW

**Comment by JeremyWeed** [comment]
Were you able to get your code to run?  I see your files are .txt, not .cpp

**Comment by JZ0024** [comment]
It's still not running. I've tried copying the commands from the ROS catkin_create_pkg tutorial and sourcing setup.bash and it's still not recognizing the package... 
I tried uploading my code as .cpp, but it didn't allow me to. Does that also have something to do with my package not running?

**Comment by JeremyWeed** [comment]
Nah, it's fine for now.  I'll add you to the repo and next meeting we can discuss what you want to do

**Comment by JZ0024** [comment]
Thanks! I got the publisher/subscriber running. It turned out I was putting my code in the wrong folder

**Pull request closed without merging**
